---
type: seq
sequence:
    - type: map
      mapping: 
        "name":
            type: str
            required: yes
        "ip":
            type: str
            required: no
        "enabled_ports":
            type: seq
            sequence:
                - type: int
                  range: { min: 1, max: 65535 }
        "vlans":
            type: seq
            sequence:
                - type: int
                  enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 98, 99]
        "admin_email":
            type: str
            required: no
            pattern: /@/



